/* Auto-generated by genmsg_cpp for file /home/ras/ros/ros-pkg/IGVC2013/imu_filter/msg/FilteredIMUData.msg */
#ifndef IMU_FILTER_MESSAGE_FILTEREDIMUDATA_H
#define IMU_FILTER_MESSAGE_FILTEREDIMUDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Vector3.h"

namespace imu_filter
{
template <class ContainerAllocator>
struct FilteredIMUData_ {
  typedef FilteredIMUData_<ContainerAllocator> Type;

  FilteredIMUData_()
  : header()
  , acceleration()
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  FilteredIMUData_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , acceleration(_alloc)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  acceleration;

  typedef double _roll_type;
  double roll;

  typedef double _pitch_type;
  double pitch;

  typedef double _yaw_type;
  double yaw;


  typedef boost::shared_ptr< ::imu_filter::FilteredIMUData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_filter::FilteredIMUData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FilteredIMUData
typedef  ::imu_filter::FilteredIMUData_<std::allocator<void> > FilteredIMUData;

typedef boost::shared_ptr< ::imu_filter::FilteredIMUData> FilteredIMUDataPtr;
typedef boost::shared_ptr< ::imu_filter::FilteredIMUData const> FilteredIMUDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::imu_filter::FilteredIMUData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::imu_filter::FilteredIMUData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace imu_filter

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::imu_filter::FilteredIMUData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::imu_filter::FilteredIMUData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::imu_filter::FilteredIMUData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3b992381865faf3f0d8287b533e18895";
  }

  static const char* value(const  ::imu_filter::FilteredIMUData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3b992381865faf3fULL;
  static const uint64_t static_value2 = 0x0d8287b533e18895ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_filter::FilteredIMUData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "imu_filter/FilteredIMUData";
  }

  static const char* value(const  ::imu_filter::FilteredIMUData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::imu_filter::FilteredIMUData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
#velocity information. z is always zero.\n\
geometry_msgs/Vector3 acceleration\n\
\n\
#yaw pitch and roll\n\
float64 roll    #roll from the imu\n\
float64 pitch   #pitch from the imu\n\
float64 yaw     #yaw from the imu\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::imu_filter::FilteredIMUData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::imu_filter::FilteredIMUData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::imu_filter::FilteredIMUData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::imu_filter::FilteredIMUData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.acceleration);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FilteredIMUData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_filter::FilteredIMUData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::imu_filter::FilteredIMUData_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acceleration: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IMU_FILTER_MESSAGE_FILTEREDIMUDATA_H

