"""autogenerated by genpy from PSoC_Listener/PSoC.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PSoC(genpy.Message):
  _md5sum = "68977ad81a156d35a01ad71eb7bba027"
  _type = "PSoC_Listener/PSoC"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 left_enc
int32 right_enc
int16 vel_v
int16 vel_w
int64 time
uint16 rate

"""
  __slots__ = ['left_enc','right_enc','vel_v','vel_w','time','rate']
  _slot_types = ['int32','int32','int16','int16','int64','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_enc,right_enc,vel_v,vel_w,time,rate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PSoC, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_enc is None:
        self.left_enc = 0
      if self.right_enc is None:
        self.right_enc = 0
      if self.vel_v is None:
        self.vel_v = 0
      if self.vel_w is None:
        self.vel_w = 0
      if self.time is None:
        self.time = 0
      if self.rate is None:
        self.rate = 0
    else:
      self.left_enc = 0
      self.right_enc = 0
      self.vel_v = 0
      self.vel_w = 0
      self.time = 0
      self.rate = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2i2hqH.pack(_x.left_enc, _x.right_enc, _x.vel_v, _x.vel_w, _x.time, _x.rate))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.left_enc, _x.right_enc, _x.vel_v, _x.vel_w, _x.time, _x.rate,) = _struct_2i2hqH.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2i2hqH.pack(_x.left_enc, _x.right_enc, _x.vel_v, _x.vel_w, _x.time, _x.rate))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.left_enc, _x.right_enc, _x.vel_v, _x.vel_w, _x.time, _x.rate,) = _struct_2i2hqH.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2i2hqH = struct.Struct("<2i2hqH")
