/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.0 Component Pack 3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <VDAC8_1.h>
#include <VDAC8_2.h>
#include <Err_LED_1_aliases.h>
#include <Err_LED_1.h>
#include <SDA_1_aliases.h>
#include <SDA_1.h>
#include <SCL_1_aliases.h>
#include <SCL_1.h>
#include <I2C.h>
#include <Clock_1.h>
#include <Servo.h>
#include <Y0_aliases.h>
#include <Servo0_aliases.h>
#include <Servo0.h>
#include <Servo1_aliases.h>
#include <Servo1.h>
#include <VDAC8_3.h>
#include <Test_Button_1_aliases.h>
#include <Test_Button_1.h>
#include <X1_aliases.h>
#include <Test_Button_2_aliases.h>
#include <Test_Button_2.h>
#include <Y1_aliases.h>
#include <X0_aliases.h>
#include <Center_aliases.h>
#include <Err_LED_2_aliases.h>
#include <Err_LED_2.h>
#include <Button_1.h>
#include <Button_2.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
