"""autogenerated by genpy from ocean_server_imu/RawData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class RawData(genpy.Message):
  _md5sum = "7d50e97be88e5cabe4ddd0a28a2e340f"
  _type = "ocean_server_imu/RawData"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

float64 yaw
float64 pitch
float64 roll

float64 temperature
float64 depth

float64 magnetic_vector_length
geometry_msgs/Vector3 magnetic

float64 acceleration_vector_length
geometry_msgs/Vector3 acceleration

float64 gyroscope_vector_length
geometry_msgs/Vector3 gyroscope
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['header','yaw','pitch','roll','temperature','depth','magnetic_vector_length','magnetic','acceleration_vector_length','acceleration','gyroscope_vector_length','gyroscope']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','geometry_msgs/Vector3','float64','geometry_msgs/Vector3','float64','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,yaw,pitch,roll,temperature,depth,magnetic_vector_length,magnetic,acceleration_vector_length,acceleration,gyroscope_vector_length,gyroscope

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RawData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.yaw is None:
        self.yaw = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.roll is None:
        self.roll = 0.
      if self.temperature is None:
        self.temperature = 0.
      if self.depth is None:
        self.depth = 0.
      if self.magnetic_vector_length is None:
        self.magnetic_vector_length = 0.
      if self.magnetic is None:
        self.magnetic = geometry_msgs.msg.Vector3()
      if self.acceleration_vector_length is None:
        self.acceleration_vector_length = 0.
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.gyroscope_vector_length is None:
        self.gyroscope_vector_length = 0.
      if self.gyroscope is None:
        self.gyroscope = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.yaw = 0.
      self.pitch = 0.
      self.roll = 0.
      self.temperature = 0.
      self.depth = 0.
      self.magnetic_vector_length = 0.
      self.magnetic = geometry_msgs.msg.Vector3()
      self.acceleration_vector_length = 0.
      self.acceleration = geometry_msgs.msg.Vector3()
      self.gyroscope_vector_length = 0.
      self.gyroscope = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_17d.pack(_x.yaw, _x.pitch, _x.roll, _x.temperature, _x.depth, _x.magnetic_vector_length, _x.magnetic.x, _x.magnetic.y, _x.magnetic.z, _x.acceleration_vector_length, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.gyroscope_vector_length, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.magnetic is None:
        self.magnetic = geometry_msgs.msg.Vector3()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.gyroscope is None:
        self.gyroscope = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 136
      (_x.yaw, _x.pitch, _x.roll, _x.temperature, _x.depth, _x.magnetic_vector_length, _x.magnetic.x, _x.magnetic.y, _x.magnetic.z, _x.acceleration_vector_length, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.gyroscope_vector_length, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z,) = _struct_17d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_17d.pack(_x.yaw, _x.pitch, _x.roll, _x.temperature, _x.depth, _x.magnetic_vector_length, _x.magnetic.x, _x.magnetic.y, _x.magnetic.z, _x.acceleration_vector_length, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.gyroscope_vector_length, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.magnetic is None:
        self.magnetic = geometry_msgs.msg.Vector3()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.gyroscope is None:
        self.gyroscope = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 136
      (_x.yaw, _x.pitch, _x.roll, _x.temperature, _x.depth, _x.magnetic_vector_length, _x.magnetic.x, _x.magnetic.y, _x.magnetic.z, _x.acceleration_vector_length, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.gyroscope_vector_length, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z,) = _struct_17d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_17d = struct.Struct("<17d")
