/* Auto-generated by genmsg_cpp for file /home/ras/ros/ros-pkg/IGVC2013/PSoC_Listener/msg/Encoder.msg */
#ifndef PSOC_LISTENER_MESSAGE_ENCODER_H
#define PSOC_LISTENER_MESSAGE_ENCODER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace PSoC_Listener
{
template <class ContainerAllocator>
struct Encoder_ {
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
  : left(0)
  , right(0)
  , time(0)
  {
  }

  Encoder_(const ContainerAllocator& _alloc)
  : left(0)
  , right(0)
  , time(0)
  {
  }

  typedef int32_t _left_type;
  int32_t left;

  typedef int32_t _right_type;
  int32_t right;

  typedef uint64_t _time_type;
  uint64_t time;


  typedef boost::shared_ptr< ::PSoC_Listener::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::PSoC_Listener::Encoder_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Encoder
typedef  ::PSoC_Listener::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::PSoC_Listener::Encoder> EncoderPtr;
typedef boost::shared_ptr< ::PSoC_Listener::Encoder const> EncoderConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::PSoC_Listener::Encoder_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::PSoC_Listener::Encoder_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace PSoC_Listener

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::PSoC_Listener::Encoder_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::PSoC_Listener::Encoder_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::PSoC_Listener::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ef8185b7dae1d13c638e420b601988c1";
  }

  static const char* value(const  ::PSoC_Listener::Encoder_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xef8185b7dae1d13cULL;
  static const uint64_t static_value2 = 0x638e420b601988c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::PSoC_Listener::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "PSoC_Listener/Encoder";
  }

  static const char* value(const  ::PSoC_Listener::Encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::PSoC_Listener::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 left\n\
int32 right\n\
uint64 time\n\
\n\
";
  }

  static const char* value(const  ::PSoC_Listener::Encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::PSoC_Listener::Encoder_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::PSoC_Listener::Encoder_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.left);
    stream.next(m.right);
    stream.next(m.time);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Encoder_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::PSoC_Listener::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::PSoC_Listener::Encoder_<ContainerAllocator> & v) 
  {
    s << indent << "left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right);
    s << indent << "time: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.time);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PSOC_LISTENER_MESSAGE_ENCODER_H

