/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.0 Component Pack 3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <USBUART.h>
#include <USBUART_audio.h>
#include <USBUART_cdc.h>
#include <USBUART_hid.h>
#include <USBUART_midi.h>
#include <Trigger.h>
#include <Trigger_aliases.h>
#include <Echo_0.h>
#include <Echo_0_aliases.h>
#include <Echo_ISR_1.h>
#include <Echo_ISR_0.h>
#include <Echo_1.h>
#include <Echo_1_aliases.h>
#include <Timer_ISR.h>
#include <Timer_1.h>
#include <USBUART_Dm_aliases.h>
#include <USBUART_Dp.h>
#include <USBUART_Dp_aliases.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/
