/* Auto-generated by genmsg_cpp for file /home/ras/ros-pkg/igvc2011/enterpras_common/microcontroller_interface/msg/Telemetry.msg */
#ifndef MICROCONTROLLER_INTERFACE_MESSAGE_TELEMETRY_H
#define MICROCONTROLLER_INTERFACE_MESSAGE_TELEMETRY_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "roslib/Header.h"

namespace microcontroller_interface
{
template <class ContainerAllocator>
struct Telemetry_ : public ros::Message
{
  typedef Telemetry_<ContainerAllocator> Type;

  Telemetry_()
  : header()
  , command(0)
  , actual(0)
  {
  }

  Telemetry_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , command(0)
  , actual(0)
  {
  }

  typedef  ::roslib::Header_<ContainerAllocator>  _header_type;
   ::roslib::Header_<ContainerAllocator>  header;

  typedef int32_t _command_type;
  int32_t command;

  typedef int32_t _actual_type;
  int32_t actual;


private:
  static const char* __s_getDataType_() { return "microcontroller_interface/Telemetry"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "099f23789666af6c5996c42d9aa81d25"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
\n\
int32 command\n\
int32 actual\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, command);
    ros::serialization::serialize(stream, actual);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, command);
    ros::serialization::deserialize(stream, actual);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(command);
    size += ros::serialization::serializationLength(actual);
    return size;
  }

  typedef boost::shared_ptr< ::microcontroller_interface::Telemetry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microcontroller_interface::Telemetry_<ContainerAllocator>  const> ConstPtr;
}; // struct Telemetry
typedef  ::microcontroller_interface::Telemetry_<std::allocator<void> > Telemetry;

typedef boost::shared_ptr< ::microcontroller_interface::Telemetry> TelemetryPtr;
typedef boost::shared_ptr< ::microcontroller_interface::Telemetry const> TelemetryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::microcontroller_interface::Telemetry_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::microcontroller_interface::Telemetry_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace microcontroller_interface

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::microcontroller_interface::Telemetry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "099f23789666af6c5996c42d9aa81d25";
  }

  static const char* value(const  ::microcontroller_interface::Telemetry_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x099f23789666af6cULL;
  static const uint64_t static_value2 = 0x5996c42d9aa81d25ULL;
};

template<class ContainerAllocator>
struct DataType< ::microcontroller_interface::Telemetry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "microcontroller_interface/Telemetry";
  }

  static const char* value(const  ::microcontroller_interface::Telemetry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::microcontroller_interface::Telemetry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
int32 command\n\
int32 actual\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::microcontroller_interface::Telemetry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::microcontroller_interface::Telemetry_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::microcontroller_interface::Telemetry_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.command);
    stream.next(m.actual);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Telemetry_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microcontroller_interface::Telemetry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::microcontroller_interface::Telemetry_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::roslib::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "command: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command);
    s << indent << "actual: ";
    Printer<int32_t>::stream(s, indent + "  ", v.actual);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MICROCONTROLLER_INTERFACE_MESSAGE_TELEMETRY_H

