/* Auto-generated by genmsg_cpp for file /home/ras/IGVC2013/uc_interface_2013/msg/Telemetry.msg */
#ifndef UC_INTERFACE_2013_MESSAGE_TELEMETRY_H
#define UC_INTERFACE_2013_MESSAGE_TELEMETRY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace uc_interface_2013
{
template <class ContainerAllocator>
struct Telemetry_ {
  typedef Telemetry_<ContainerAllocator> Type;

  Telemetry_()
  : header()
  , command(0)
  , actual(0)
  {
  }

  Telemetry_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , command(0)
  , actual(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _command_type;
  int32_t command;

  typedef int32_t _actual_type;
  int32_t actual;


  typedef boost::shared_ptr< ::uc_interface_2013::Telemetry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uc_interface_2013::Telemetry_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Telemetry
typedef  ::uc_interface_2013::Telemetry_<std::allocator<void> > Telemetry;

typedef boost::shared_ptr< ::uc_interface_2013::Telemetry> TelemetryPtr;
typedef boost::shared_ptr< ::uc_interface_2013::Telemetry const> TelemetryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::uc_interface_2013::Telemetry_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::uc_interface_2013::Telemetry_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace uc_interface_2013

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::uc_interface_2013::Telemetry_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::uc_interface_2013::Telemetry_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::uc_interface_2013::Telemetry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "099f23789666af6c5996c42d9aa81d25";
  }

  static const char* value(const  ::uc_interface_2013::Telemetry_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x099f23789666af6cULL;
  static const uint64_t static_value2 = 0x5996c42d9aa81d25ULL;
};

template<class ContainerAllocator>
struct DataType< ::uc_interface_2013::Telemetry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uc_interface_2013/Telemetry";
  }

  static const char* value(const  ::uc_interface_2013::Telemetry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::uc_interface_2013::Telemetry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
int32 command\n\
int32 actual\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::uc_interface_2013::Telemetry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::uc_interface_2013::Telemetry_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::uc_interface_2013::Telemetry_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::uc_interface_2013::Telemetry_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.command);
    stream.next(m.actual);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Telemetry_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uc_interface_2013::Telemetry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::uc_interface_2013::Telemetry_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "command: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command);
    s << indent << "actual: ";
    Printer<int32_t>::stream(s, indent + "  ", v.actual);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UC_INTERFACE_2013_MESSAGE_TELEMETRY_H

